# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3da7b09f09726a3cef87a87a17b3755749397d1fdda2789fc9455c43326d86b2cc057e244ea10639cdf6aea8d673fc246b2ac1b077adfe9c34b9713dd334fdb0

test:
  secret_key_base: cd3d41245b5a137849c43b5f6f8f6e0adaec18ad0176f3456d270dc31579c0c88b527d67747cfec48c55ed2f660c41a4e0087d88cb9edeefbbb9f02a52dedead

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
